name: dart_date
description: date manipulation library. DateTime extensions.
version: 1.0.0
homepage: https://github.com/sntiagoma/dart_date

environment:
  sdk: '>=2.6.0 <3.0.0'

dependencies:
  intl: ^0.15.7
  timeago: ^2.0.9

dev_dependencies:
  test: ^1.3.0