name: dart_date
description: A date manipulation library.
version: 0.0.6
homepage: https://github.com/sntiagoma/dart_date
author: Santiago Montoya Angarita <sntiagoma@gmail.com>

environment:
  sdk: '>=2.0.0 <3.0.0'

dependencies:
  intl: ^0.15.7

dev_dependencies:
  test: ^1.3.0